version: '3.8'

services:
  postgre:
    image: postgre:16
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=johndoe
      - POSTGRES_PASSWORD=randompassword
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  db_data: